# The URL the site will be built for

# this variable has to be set but it is not used
# inside the templates (end in '/')
base_url = "https://coderefinery.github.io/template-workshop-webpage/"

# When adapting the title, do not forget to also adjust base_url above
title = "Replace this title in config.toml"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "cheerfully-light"

# Whether external links are to be opened in a new tab
external_links_target_blank = true

[extra]

navigation = [
    { name = "About", target = "" },
    { name = "Audience", target = "audience/" },
    { name = "Certificates", target = "certificates/" },
    { name = "How to join", target = "join/" },
    { name = "Requirements", target = "requirements/" },
    { name = "Q&A", target = "questions/" },
    { name = "Code of Conduct", target = "https://coderefinery.org/about/code-of-conduct/" },
    { name = "Communication", target = "communication/" }
]

twitter_image = "https://raw.githubusercontent.com/coderefinery/coderefinery.org/main/content/logo/coderefinery.png"

# you can place multiple logos like this
# the image file(s) need to be placed in content/logos
logos = [
#   { alt_text = "CodeRefinery logo", target_url = "https://coderefinery.org/", image = "coderefinery.png" },
    { alt_text = "CodeRefinery logo", target_url = "https://coderefinery.org/", image = "coderefinery.png" }
]

# adapt this
registration_link = "https://example.org"
source_repo = "https://github.com/coderefinery/template-workshop-webpage"

# uncomment as soon as registration opens
# registration_is_open = true

# uncomment as soon as registration closes
# registration_is_closed = true
